version: "3.1"
services:
  frontend:
    build:
      context: ../../front-end
      dockerfile: ./docker/dev/Dockerfile
    image: citybike-frontend
    ports:
      - 5173:5173
    volumes:
      - ../../front-end/:/run/src/app
    restart: unless-stopped