version: "3.1"
services:
  frontend:
    build:
      context: ../../front-end
      dockerfile: ./docker/prod/Dockerfile
    image: citybike-frontend
    volumes:
      - web-root:/run/web

volumes:
  web-root: