SHELL := /bin/bash

# Development venv
VIRTUAL_ENV ?= back-end/venv

# Prefix container names
export COMPOSE_PROJECT_NAME := citybike

# Database
export POSTGRES_HOST ?= localhost
export POSTGRES_DB ?= citybike
export POSTGRES_USER ?= academy
export POSTGRES_PASSWORD ?= academy
export POSTGRES_APP_DB ?= citybike
export POSTGRES_APP_DB_USER ?= academy
export POSTGRES_APP_DB_PASSWORD ?= academy
