# Generated by Django 4.2.7 on 2023-11-04 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('station_address', models.CharField(max_length=100)),
                ('coordinate_x', models.CharField(max_length=100)),
                ('coordinate_y', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date_time', models.DateTimeField(blank=True, null=True)),
                ('return_date_time', models.DateTimeField(blank=True, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('departure_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_departure_station_set', to='bikes.station')),
                ('return_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_return_station_set', to='bikes.station')),
            ],
            options={
                'db_table': 'journey',
            },
        ),
    ]
